# Generated by Django 4.2 on 2023-10-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="location",
        ),
    ]
