# Generated by Django 4.2 on 2024-07-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_category_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='location',
            field=models.IntegerField(choices=[(0, 'USA'), (1, 'UK'), (2, 'Canada'), (3, 'Australia'), (4, 'Germany'), (5, 'France'), (6, 'Italy'), (7, 'Spain')], default=0),
        ),
    ]
