# Generated by Django 4.2 on 2024-07-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='location',
            field=models.CharField(choices=[('USA', 'USA'), ('UK', 'UK')], default='USA', max_length=255),
        ),
    ]
