# Generated by Django 4.2 on 2024-10-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='location',
            field=models.CharField(choices=[('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada'), ('Other', 'Other')], default='USA', max_length=255),
        ),
    ]
