# Generated by Django 4.2 on 2023-10-28 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0002_remove_category_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (-1, "Not Started"),
                            (0, "Unconfirmed"),
                            (1, "Partially Confirmed"),
                            (2, "Confirmed"),
                        ],
                        default=-1,
                    ),
                ),
                ("order_id", models.CharField(max_length=250)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("btcvalue", models.FloatField(blank=True, null=True)),
                ("received", models.FloatField(blank=True, null=True)),
                ("txid", models.CharField(blank=True, max_length=250, null=True)),
                ("rbf", models.IntegerField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("sold", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=250)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("received", models.FloatField(blank=True, null=True)),
                ("balance", models.FloatField(blank=True, null=True)),
                ("txid", models.CharField(blank=True, max_length=250, null=True)),
                ("created_at", models.DateField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
