# Generated by Django 4.2 on 2024-03-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_telegram_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_Otp_bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('received', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=50, null=True)),
                ('txid', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('chat_id', models.CharField(max_length=250)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('log', models.BooleanField(default=False)),
            ],
        ),
    ]
